// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUd2xjf_pxtZOFmpilB6VNqY3mqaHVbj0',
    appId: '1:661164984533:web:6f81de21a6dc62b90e3a5c',
    messagingSenderId: '661164984533',
    projectId: 'fir-firebase-ab954',
    authDomain: 'fir-firebase-ab954.firebaseapp.com',
    storageBucket: 'fir-firebase-ab954.appspot.com',
    measurementId: 'G-W0WR3LJVJ9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnO2nupGpqjDnfRWU_pDZG9vU_owvf0Xw',
    appId: '1:661164984533:android:d8d84175209332a00e3a5c',
    messagingSenderId: '661164984533',
    projectId: 'fir-firebase-ab954',
    storageBucket: 'fir-firebase-ab954.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUSbJ8zlhi9FD9f8gpcZMFOjvHes06m88',
    appId: '1:661164984533:ios:bce526573eab651e0e3a5c',
    messagingSenderId: '661164984533',
    projectId: 'fir-firebase-ab954',
    storageBucket: 'fir-firebase-ab954.appspot.com',
    iosBundleId: 'com.example.demofirebaseAndroid',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUSbJ8zlhi9FD9f8gpcZMFOjvHes06m88',
    appId: '1:661164984533:ios:0bb525cea4c9672d0e3a5c',
    messagingSenderId: '661164984533',
    projectId: 'fir-firebase-ab954',
    storageBucket: 'fir-firebase-ab954.appspot.com',
    iosBundleId: 'com.example.demofirebaseAndroid.RunnerTests',
  );
}
